environment:

  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

build: off

install:
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -m pip install --disable-pip-version-check --user --upgrade pip"
  - "python setup.py install"

test_script:
  - "%PYTHON%\\python.exe test\\test_unit.py"
  - "%PYTHON%\\python.exe test\\test_fuzz.py"
