language: python
matrix:
    include:
        - python: 2.7
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true

install:
  - python setup.py install

# command to run tests
script:
- "./test/test_unit.py"
- "./test/test_fuzz.py"

# blacklist
#branches:
#  except:
#    - experimental

# whitelist
branches:
  only:
    - master
