language: python
python:
  - "2.7"

# command to run tests
script:
- "./test/test_unit.py"
- "./test/test_fuzz.py"

# blacklist
#branches:
#  except:
#    - experimental

# whitelist
branches:
  only:
    - master
