[mypy]
no_implicit_reexport=true
strict=true
files=src/fileseq
exclude=^(test/|env/|docs/|src/fileseq/parser/fileseq(Lexer|Parser|Listener|Visitor)\.py|src/fileseq/grammar/generate\.py)
python_version=3.9
# Allow untyped calls to ANTLR runtime (generated code)
disable_error_code=no-untyped-call,misc,no-any-return,unused-ignore

[mypy-antlr4.*]
ignore_missing_imports=true
